# Generated by Django 4.2.5 on 2023-10-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_portfolio_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Default description.'),
        ),
    ]
