# Generated by Django 4.2.5 on 2023-10-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_rename_name_project_title_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsinportfolio',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='projectsinportfolio',
            name='project',
        ),
        migrations.RemoveField(
            model_name='student',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
